// frontend-v2/src/renderers/form/JsonSchemaForm.tsx
import { useMemo } from "react";
import { useForm } from "react-hook-form";

import { asJsonSchema, effectiveSchema } from "@/contracts/json-schema";
import type { ActionDemoSchema, FormFieldSchema } from "@/contracts/ui-catalog";
import { ajvResolver } from "./ajv-resolver";
import { SchemaField } from "./SchemaField";

/**
 * 动态 JSON Schema 表单（对齐旧 JsonSchemaForm.vue 编排）：
 * 字段集 = input_schema.properties；必填 = schema.required ∪ params[].required；
 * 校验 = Ajv 白名单编译器（ajv-resolver）。
 */
export function JsonSchemaForm({
  formId,
  schema,
  params,
  businessFields,
  actions,
  defaultValues,
  onSubmit,
  multipart,
}: {
  formId: string;
  schema: unknown;
  params?: ActionDemoSchema["params"];
  businessFields?: FormFieldSchema[];
  actions?: ActionDemoSchema[];
  defaultValues: Record<string, unknown>;
  onSubmit: (values: Record<string, unknown>) => void;
  multipart?: ActionDemoSchema["multipart"];
}) {
  const root = useMemo(() => asJsonSchema(schema), [schema]);
  const resolved = useMemo(() => effectiveSchema(root, root), [root]);
  const properties = resolved.properties ?? {};
  const requiredNames = useMemo(() => {
    const names = new Set(resolved.required ?? []);
    for (const parameter of params ?? []) {
      if (parameter.required) names.add(parameter.name);
    }
    return names;
  }, [resolved.required, params]);
  const paramByName = useMemo(
    () =>
      new Map((params ?? []).map((parameter) => [parameter.name, parameter])),
    [params],
  );
  const businessFieldByName = useMemo(
    () => new Map((businessFields ?? []).map((field) => [field.field, field])),
    [businessFields],
  );

  const form = useForm<Record<string, unknown>>({
    defaultValues,
    resolver: ajvResolver(schema),
  });

  if (Object.keys(properties).length === 0) {
    return (
      <form id={formId} onSubmit={form.handleSubmit(onSubmit)}>
        <p className="py-6 text-center text-sm text-muted-foreground">
          此 Action 无输入字段
        </p>
      </form>
    );
  }

  return (
    <form
      id={formId}
      noValidate
      className="space-y-4"
      onSubmit={form.handleSubmit(onSubmit)}
    >
      {Object.entries(properties).map(([name, property]) => (
        <SchemaField
          key={name}
          name={name}
          schema={property}
          rootSchema={root}
          control={form.control}
          required={requiredNames.has(name)}
          title={paramByName.get(name)?.title}
          description={paramByName.get(name)?.description}
          businessField={businessFieldByName.get(name)}
          actions={actions}
          multipart={multipart}
        />
      ))}
    </form>
  );
}

// frontend/src/components/form/JsonSchemaForm.vue
<script setup lang="ts">
import { computed } from "vue";
import { asJsonSchema, effectiveSchema } from "src/contracts/json-schema";
import type { ActionDemoSchema } from "src/contracts/ui-catalog";
import type { SessionContext } from "src/api/client";
import type { FormFieldSchema } from "src/contracts/ui-catalog";
import SchemaField from "./SchemaField.vue";

const props = defineProps<{
  schema: unknown;
  modelValue: Record<string, unknown>;
  params?: ActionDemoSchema["params"];
  businessFields?: FormFieldSchema[];
  actions?: ActionDemoSchema[];
  session?: SessionContext;
  multipart?: ActionDemoSchema["multipart"];
}>();

const emit = defineEmits<{
  "update:modelValue": [value: Record<string, unknown>];
}>();

const root = computed(() => asJsonSchema(props.schema));
const resolved = computed(() => effectiveSchema(root.value, root.value));
const properties = computed(() => resolved.value.properties ?? {});
const required = computed(() => new Set(resolved.value.required ?? []));
const presentation = computed(
  () =>
    new Map(
      (props.params ?? []).map((parameter) => [parameter.name, parameter]),
    ),
);
const businessFields = computed(
  () =>
    new Map((props.businessFields ?? []).map((field) => [field.field, field])),
);

function updateField(name: string, value: unknown) {
  emit("update:modelValue", { ...props.modelValue, [name]: value });
}
</script>

<template>
  <div
    v-if="Object.keys(properties).length === 0"
    class="empty-state form-empty-state"
  >
    <q-icon name="input" size="40px" />
    <span>此 Action 无输入字段</span>
  </div>
  <q-form v-else class="schema-form">
    <SchemaField
      v-for="(property, name) in properties"
      :key="name"
      :name="name"
      :schema="property"
      :root-schema="root"
      :model-value="modelValue[name]"
      :required="
        required.has(name) || Boolean(presentation.get(name)?.required)
      "
      :title="presentation.get(name)?.title"
      :description="presentation.get(name)?.description"
      :business-field="businessFields.get(name)"
      :actions="actions"
      :session="session"
      :multipart="multipart"
      @update:model-value="updateField(name, $event)"
    />
  </q-form>
</template>
