// frontend-v2/src/renderers/form/RelationSelect.tsx
import { useEffect, useMemo, useState } from "react";

import { invokeAction } from "@/api/client";
import { useSessionCredentials } from "@/api/use-session";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { parseRelationOptions } from "@/contracts/table-data";
import type { ActionDemoSchema, FormFieldSchema } from "@/contracts/ui-catalog";

type RelationOption = { value: string | number; label: string };

/**
 * 关系选择器（旧 RelationSelect 语义）：初始/选中值加载 + 250ms 防抖远程搜索，
 * 请求契约 {search, selected, filter, page, limit} 与旧实现一致；
 * 选项控件为 Radix Select（shadcn 组件）。
 */
export function RelationSelect({
  value,
  onChange,
  label,
  field,
  action,
  disabled,
}: {
  value: unknown;
  onChange: (value: unknown) => void;
  label: string;
  field: FormFieldSchema;
  action?: ActionDemoSchema;
  disabled?: boolean;
}) {
  const session = useSessionCredentials();
  const [options, setOptions] = useState<RelationOption[]>([]);
  const [error, setError] = useState("");
  const [search, setSearch] = useState("");

  const selectedValues = useMemo(
    () =>
      typeof value === "string" || typeof value === "number" ? [value] : [],
    [value],
  );

  useEffect(() => {
    if (!action) {
      setError(
        `目录缺少关系 Action：${field.relation?.operation_id ?? "unknown"}`,
      );
      return;
    }
    const controller = new AbortController();
    const timer = window.setTimeout(
      () => {
        invokeAction(
          action,
          {
            search: search.trim() || null,
            selected: selectedValues,
            filter: {},
            page: 1,
            limit: 20,
          },
          session,
          controller.signal,
        )
          .then((result) => {
            if (result.kind !== "json")
              throw new Error("关系 Action 必须返回 JSON");
            setOptions(parseRelationOptions(result.data).items);
            setError("");
          })
          .catch((cause: unknown) => {
            if (cause instanceof Error && cause.name === "AbortError") return;
            setError(cause instanceof Error ? cause.message : String(cause));
          });
      },
      search.trim() ? 250 : 0,
    );
    return () => {
      window.clearTimeout(timer);
      controller.abort();
    };
  }, [action, search, selectedValues, session, field.relation?.operation_id]);

  const displayOptions = useMemo(() => {
    const merged = [...options];
    for (const selected of selectedValues) {
      if (!merged.some((option) => Object.is(option.value, selected))) {
        merged.push({ value: selected, label: String(selected) });
      }
    }
    return merged;
  }, [options, selectedValues]);

  return (
    <div className="space-y-1.5">
      <Input
        placeholder={`搜索${label}`}
        aria-label={`搜索${label}`}
        className="h-8"
        value={search}
        onChange={(event) => setSearch(event.target.value)}
        disabled={disabled || !action}
      />
      <Select
        disabled={disabled || !action}
        value={
          selectedValues[0] === undefined
            ? undefined
            : String(selectedValues[0])
        }
        onValueChange={(raw) => {
          const option = displayOptions.find(
            (candidate) => String(candidate.value) === raw,
          );
          onChange(option?.value);
        }}
      >
        <SelectTrigger aria-label={label} className="w-full">
          <SelectValue placeholder="未选择" />
        </SelectTrigger>
        <SelectContent>
          {displayOptions.map((option) => (
            <SelectItem key={String(option.value)} value={String(option.value)}>
              {option.label}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>
      {error && <p className="text-xs text-destructive">{error}</p>}
    </div>
  );
}

// frontend/src/components/form/RelationSelect.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { invokeAction, type SessionContext } from "src/api/client";
import { parseRelationOptions } from "src/contracts/table-data";
import type {
  ActionDemoSchema,
  FormFieldSchema,
} from "src/contracts/ui-catalog";

const props = defineProps<{
  label: string;
  modelValue: unknown;
  field: FormFieldSchema;
  action?: ActionDemoSchema;
  session: SessionContext;
  disabled?: boolean;
}>();

const emit = defineEmits<{ "update:modelValue": [value: unknown] }>();
const options = ref<Array<{ value: string | number; label: string }>>([]);
const loading = ref(false);
const error = ref("");
let controller: AbortController | undefined;
let timer: number | undefined;
const selectValue = computed(() =>
  typeof props.modelValue === "string" || typeof props.modelValue === "number"
    ? props.modelValue
    : undefined,
);

function selectedValues(): Array<string | number> {
  return typeof props.modelValue === "string" ||
    typeof props.modelValue === "number"
    ? [props.modelValue]
    : [];
}

async function load(search?: string) {
  if (!props.action) {
    error.value = `目录缺少关系 Action：${props.field.relation?.operation_id ?? "unknown"}`;
    return;
  }
  controller?.abort();
  controller = new AbortController();
  loading.value = true;
  error.value = "";
  try {
    const result = await invokeAction(
      props.action,
      {
        search: search?.trim() || null,
        selected: selectedValues(),
        filter: {},
        page: 1,
        limit: 20,
      },
      props.session,
      controller.signal,
    );
    if (result.kind !== "json") throw new Error("关系 Action 必须返回 JSON");
    options.value = parseRelationOptions(result.data).items;
  } catch (cause) {
    if (cause instanceof Error && cause.name === "AbortError") return;
    error.value = cause instanceof Error ? cause.message : String(cause);
  } finally {
    loading.value = false;
  }
}

function remoteSearch(value: string) {
  if (timer !== undefined) window.clearTimeout(timer);
  timer = window.setTimeout(() => void load(value), 250);
}

function filterOptions(value: string, update: (callback: () => void) => void) {
  remoteSearch(value);
  update(() => undefined);
}

watch(
  () => props.modelValue,
  () => void load(),
);
onMounted(() => void load());
onBeforeUnmount(() => {
  controller?.abort();
  if (timer !== undefined) window.clearTimeout(timer);
});
</script>

<template>
  <div class="relation-select">
    <q-select
      :model-value="selectValue"
      :options="options"
      option-value="value"
      option-label="label"
      :disabled="disabled || !action"
      :loading="loading"
      :label="label"
      outlined
      dense
      emit-value
      map-options
      use-input
      input-debounce="0"
      clearable
      @filter="filterOptions"
      @update:model-value="emit('update:modelValue', $event)"
    />
    <small v-if="error" class="field-error">{{ error }}</small>
  </div>
</template>
