// frontend-v2/src/renderers/form/SchemaField.tsx
import { useId, useMemo, useState } from "react";
import { Controller, type Control } from "react-hook-form";

import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { effectiveSchema, type JsonSchemaNode } from "@/contracts/json-schema";
import type { ActionDemoSchema, FormFieldSchema } from "@/contracts/ui-catalog";
import { RelationSelect } from "./RelationSelect";
import { resolveFormControl } from "./form-control";

/**
 * 单字段控件分支表（对齐旧 SchemaField.vue）：widget hint → 显式控件落点，
 * 无 hint 时按 JSON Schema 类型/格式选择（分支逻辑见 form-control.ts）。
 */
export function SchemaField({
  name,
  schema,
  rootSchema,
  control,
  required,
  title,
  description,
  businessField,
  actions,
}: {
  name: string;
  schema: JsonSchemaNode;
  rootSchema: JsonSchemaNode;
  control: Control<Record<string, unknown>>;
  required: boolean;
  title?: string;
  description?: string;
  businessField?: FormFieldSchema;
  actions?: ActionDemoSchema[];
}) {
  const id = useId();
  const resolved = effectiveSchema(rootSchema, schema);
  const type = Array.isArray(resolved.type)
    ? resolved.type.find((item) => item !== "null")
    : resolved.type;
  const label = title || resolved.title || name;
  const fieldControl = resolveFormControl(
    businessField?.widget,
    type,
    Boolean(resolved.enum),
    resolved.format,
  );
  const relationAction = businessField?.relation
    ? actions?.find(
        (action) =>
          action.operation_id === businessField.relation?.operation_id,
      )
    : undefined;
  const help =
    description || businessField?.description || resolved.description;

  return (
    <Controller
      control={control}
      name={name}
      render={({ field, fieldState }) => (
        <div className="space-y-1.5">
          {fieldControl !== "toggle" && (
            <Label htmlFor={id}>
              {label}
              {required && <span className="text-destructive"> *</span>}
            </Label>
          )}
          <FieldControl
            id={id}
            control={fieldControl}
            type={type}
            value={field.value}
            onChange={field.onChange}
            resolved={resolved}
            disabled={businessField?.read_only}
            label={label}
            businessField={businessField}
            relationAction={relationAction}
          />
          {help && <p className="text-xs text-muted-foreground">{help}</p>}
          {fieldState.error && (
            <p className="text-xs text-destructive" role="alert">
              {fieldState.error.message}
            </p>
          )}
        </div>
      )}
    />
  );
}

function FieldControl({
  id,
  control,
  type,
  value,
  onChange,
  resolved,
  disabled,
  label,
  businessField,
  relationAction,
}: {
  id: string;
  control: ReturnType<typeof resolveFormControl>;
  type: string | undefined;
  value: unknown;
  onChange: (value: unknown) => void;
  resolved: JsonSchemaNode;
  disabled?: boolean;
  label: string;
  businessField?: FormFieldSchema;
  relationAction?: ActionDemoSchema;
}) {
  if (control === "relation") {
    if (!businessField?.relation) {
      return (
        <p className="text-xs text-destructive">关系控件缺少 relation 契约</p>
      );
    }
    return (
      <RelationSelect
        id={id}
        value={value}
        onChange={onChange}
        label={label}
        field={businessField}
        action={relationAction}
        disabled={disabled}
      />
    );
  }

  if (control === "enum") {
    const options = (resolved.enum ?? []).map((entry) => ({
      key: JSON.stringify(entry),
      label: typeof entry === "string" ? entry : JSON.stringify(entry),
      value: entry,
    }));
    const selected = JSON.stringify(value);
    return (
      <select
        id={id}
        aria-label={label}
        className="border-input flex h-9 w-full rounded-md border bg-transparent px-2 text-sm shadow-xs outline-none focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:opacity-50"
        disabled={disabled}
        value={
          options.some((option) => option.key === selected) ? selected : ""
        }
        onChange={(event) => {
          const option = options.find(
            (candidate) => candidate.key === event.target.value,
          );
          onChange(option?.value);
        }}
      >
        <option value="">未选择</option>
        {options.map((option) => (
          <option key={option.key} value={option.key}>
            {option.label}
          </option>
        ))}
      </select>
    );
  }

  if (control === "toggle") {
    return (
      <div className="flex items-center gap-2">
        <Checkbox
          id={id}
          checked={Boolean(value)}
          disabled={disabled}
          onCheckedChange={(checked) => onChange(checked === true)}
        />
        <Label htmlFor={id}>{label}</Label>
      </div>
    );
  }

  if (control === "number") {
    return (
      <Input
        id={id}
        type="number"
        step={type === "integer" ? "1" : "0.1"}
        min={resolved.minimum}
        max={resolved.maximum}
        disabled={disabled}
        value={typeof value === "number" ? value : ""}
        onChange={(event) => {
          const raw = event.target.value;
          if (!raw) return onChange(undefined);
          const parsed = Number(raw);
          if (Number.isFinite(parsed)) onChange(parsed);
        }}
      />
    );
  }

  if (control === "date_time") {
    return (
      <Input
        id={id}
        type="datetime-local"
        disabled={disabled}
        value={
          typeof value === "string" || typeof value === "number" ? value : ""
        }
        onChange={(event) => onChange(event.target.value || undefined)}
      />
    );
  }

  if (control === "color") {
    return (
      <input
        id={id}
        type="color"
        aria-label={label}
        disabled={disabled}
        value={typeof value === "string" ? value : "#000000"}
        onChange={(event) => onChange(event.target.value)}
      />
    );
  }

  if (control === "json") {
    return (
      <JsonDraftInput
        id={id}
        value={value}
        onChange={onChange}
        disabled={disabled}
      />
    );
  }

  if (control === "textarea") {
    return (
      <textarea
        id={id}
        rows={4}
        disabled={disabled}
        className="border-input flex w-full rounded-md border bg-transparent px-3 py-2 text-sm shadow-xs outline-none focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:opacity-50"
        maxLength={resolved.maxLength}
        value={typeof value === "string" ? value : String(value ?? "")}
        onChange={(event) => onChange(event.target.value || undefined)}
      />
    );
  }

  const inputType =
    control === "password" || control === "email" || control === "url"
      ? control
      : "text";
  return (
    <Input
      id={id}
      type={inputType}
      disabled={disabled}
      maxLength={resolved.maxLength}
      value={typeof value === "string" ? value : String(value ?? "")}
      onChange={(event) => onChange(event.target.value || undefined)}
    />
  );
}

/// JSON 控件：草稿失焦时解析，非法 JSON 就地提示（对齐旧 SchemaField 的 commitJson）。
function JsonDraftInput({
  id,
  value,
  onChange,
  disabled,
}: {
  id: string;
  value: unknown;
  onChange: (value: unknown) => void;
  disabled?: boolean;
}) {
  const [draft, setDraft] = useState(() =>
    value === undefined ? "" : JSON.stringify(value, null, 2),
  );
  const [error, setError] = useState("");
  const serialized = useMemo(
    () => (value === undefined ? "" : JSON.stringify(value, null, 2)),
    [value],
  );

  return (
    <div className="space-y-1">
      <textarea
        id={id}
        rows={6}
        disabled={disabled}
        className="border-input flex w-full rounded-md border bg-transparent px-3 py-2 font-mono text-xs shadow-xs outline-none focus-visible:ring-ring/50 focus-visible:ring-[3px] disabled:opacity-50"
        value={draft}
        onFocus={() => setDraft(serialized)}
        onChange={(event) => setDraft(event.target.value)}
        onBlur={() => {
          if (!draft.trim()) {
            onChange(undefined);
            setError("");
            return;
          }
          try {
            onChange(JSON.parse(draft));
            setError("");
          } catch (cause) {
            setError(cause instanceof Error ? cause.message : String(cause));
          }
        }}
      />
      {error && (
        <p className="text-xs text-destructive" role="alert">
          {error}
        </p>
      )}
    </div>
  );
}

// frontend/src/components/form/SchemaField.vue
<script setup lang="ts">
import { computed, ref, useId, watch } from "vue";
import {
  effectiveSchema,
  type JsonSchemaNode,
} from "src/contracts/json-schema";
import type { SessionContext } from "src/api/client";
import type {
  ActionDemoSchema,
  FormFieldSchema,
} from "src/contracts/ui-catalog";
import RelationSelect from "./RelationSelect.vue";
import { resolveFormControl } from "./form-control";

const props = defineProps<{
  name: string;
  schema: JsonSchemaNode;
  rootSchema: JsonSchemaNode;
  modelValue: unknown;
  required: boolean;
  title?: string;
  description?: string;
  businessField?: FormFieldSchema;
  actions?: ActionDemoSchema[];
  session?: SessionContext;
  multipart?: ActionDemoSchema["multipart"];
}>();

const emit = defineEmits<{ "update:modelValue": [value: unknown] }>();

const resolved = computed(() =>
  effectiveSchema(props.rootSchema, props.schema),
);
const type = computed(() => {
  const value = resolved.value.type;
  return Array.isArray(value) ? value.find((item) => item !== "null") : value;
});
const label = computed(() => props.title || resolved.value.title || props.name);
const relationAction = computed(() =>
  props.actions?.find(
    (action) =>
      action.operation_id === props.businessField?.relation?.operation_id,
  ),
);
const numericMinimum = computed(() => {
  if (typeof resolved.value.minimum === "number") return resolved.value.minimum;
  const value = props.businessField?.validation?.minimum;
  if (value === undefined) return undefined;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
});
const numericMaximum = computed(() => {
  if (typeof resolved.value.maximum === "number") return resolved.value.maximum;
  const value = props.businessField?.validation?.maximum;
  if (value === undefined) return undefined;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
});
const dateValue = computed(() =>
  typeof props.modelValue === "string" || typeof props.modelValue === "number"
    ? props.modelValue
    : undefined,
);
const control = computed(() =>
  resolveFormControl(
    props.businessField?.widget,
    type.value,
    Boolean(resolved.value.enum),
    resolved.value.format,
  ),
);
const inputType = computed(() => {
  if (
    control.value === "textarea" ||
    control.value === "password" ||
    control.value === "email" ||
    control.value === "url" ||
    control.value === "color"
  )
    return control.value;
  return "text";
});
const enumOptions = computed(() =>
  (resolved.value.enum ?? []).map((value) => ({
    key: JSON.stringify(value),
    label: typeof value === "string" ? value : JSON.stringify(value),
    value,
  })),
);
const selectedEnumKey = computed(() => {
  const key = JSON.stringify(props.modelValue);
  return enumOptions.value.some((option) => option.key === key)
    ? key
    : undefined;
});
const isJson = computed(() => control.value === "json");
const jsonDraft = ref("");
const jsonError = ref("");
const uploadInputId = useId();
const isBinary = computed(() => {
  if (resolved.value.format === "binary") return true;
  return (
    type.value === "array" &&
    effectiveSchema(props.rootSchema, resolved.value.items ?? {}).format ===
      "binary"
  );
});
const isMultipleFiles = computed(
  () => type.value === "array" && isBinary.value,
);
const selectedFileNames = computed(() => {
  if (props.modelValue instanceof File) return props.modelValue.name;
  if (Array.isArray(props.modelValue))
    return props.modelValue
      .filter((value) => value instanceof File)
      .map((file) => file.name)
      .join("、");
  return "";
});

watch(
  () => props.modelValue,
  (value) => {
    if (!isJson.value) return;
    jsonDraft.value = value === undefined ? "" : JSON.stringify(value, null, 2);
  },
  { immediate: true },
);

function update(value: unknown) {
  emit("update:modelValue", value);
}

function updateEnum(key: string) {
  const option = enumOptions.value.find((candidate) => candidate.key === key);
  update(option?.value);
}

function updateNumber(value: string | number | null) {
  if (value === null || value === "") {
    update(undefined);
    return;
  }
  const parsed = Number(value);
  if (Number.isFinite(parsed)) update(parsed);
}

function commitJson() {
  if (!jsonDraft.value.trim()) {
    update(undefined);
    jsonError.value = "";
    return;
  }
  try {
    update(JSON.parse(jsonDraft.value));
    jsonError.value = "";
  } catch (error) {
    jsonError.value = error instanceof Error ? error.message : String(error);
  }
}

function selectFiles(event: Event) {
  const target = event.target;
  if (!(target instanceof HTMLInputElement)) return;
  const files = Array.from(target.files ?? []);
  update(isMultipleFiles.value ? files : files[0]);
}
</script>

<template>
  <div class="schema-field">
    <div v-if="isBinary" class="upload-control">
      <label :for="uploadInputId" class="upload-label">
        {{ label }}<span v-if="required"> *</span>
      </label>
      <input
        :id="uploadInputId"
        type="file"
        :multiple="isMultipleFiles"
        :accept="multipart?.allowed_content_types.join(',')"
        @change="selectFiles"
      />
      <small v-if="selectedFileNames">已选择：{{ selectedFileNames }}</small>
      <small v-if="multipart">
        单文件不超过 {{ multipart.max_file_bytes }} bytes；最多
        {{ multipart.max_files }} 个文件
      </small>
    </div>
    <RelationSelect
      v-else-if="control === 'relation' && businessField?.relation && session"
      :model-value="modelValue"
      :label="label"
      :field="businessField"
      :action="relationAction"
      :session="session"
      :disabled="businessField.read_only"
      @update:model-value="update"
    />
    <q-input
      v-else-if="control === 'relation'"
      :model-value="''"
      :label="label"
      outlined
      dense
      disable
      error
      error-message="关系控件缺少 relation 或 session 契约"
    />
    <q-select
      v-else-if="control === 'enum'"
      :model-value="selectedEnumKey"
      :options="enumOptions"
      option-value="key"
      option-label="label"
      :disabled="businessField?.read_only"
      :label="label"
      outlined
      dense
      emit-value
      map-options
      clearable
      @update:model-value="updateEnum"
    />
    <q-toggle
      v-else-if="control === 'toggle'"
      :model-value="Boolean(modelValue)"
      :disabled="businessField?.read_only"
      :label="label"
      @update:model-value="update"
    />
    <q-input
      v-else-if="control === 'number'"
      :model-value="typeof modelValue === 'number' ? modelValue : undefined"
      type="number"
      :label="label"
      outlined
      dense
      :step="
        type === 'integer' || businessField?.widget === 'integer' ? '1' : '0.1'
      "
      :min="numericMinimum"
      :max="numericMaximum"
      :disabled="businessField?.read_only"
      @update:model-value="updateNumber"
    />
    <q-input
      v-else-if="control === 'date_time'"
      :model-value="dateValue"
      type="datetime-local"
      :label="label"
      outlined
      dense
      :disabled="businessField.read_only"
      @update:model-value="update"
    />
    <q-input
      v-else-if="control !== 'json'"
      :model-value="
        typeof modelValue === 'string' ? modelValue : String(modelValue ?? '')
      "
      :type="inputType"
      :label="label"
      outlined
      dense
      :rows="control === 'textarea' ? 4 : undefined"
      :maxlength="resolved.maxLength ?? businessField?.validation?.max_length"
      :disabled="businessField?.read_only"
      clearable
      @update:model-value="update"
    />
    <q-input
      v-else
      v-model="jsonDraft"
      type="textarea"
      :label="label"
      outlined
      dense
      :rows="6"
      :disabled="businessField?.read_only"
      :error="Boolean(jsonError)"
      :error-message="jsonError"
      @blur="commitJson"
    />
    <div
      v-if="description || businessField?.description || resolved.description"
      class="field-help"
    >
      {{ description || businessField?.description || resolved.description }}
    </div>
  </div>
</template>
