// frontend/src/custom/views/DemoItemInsight.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { z } from "zod";

import { invokeAction } from "@/api/client";
import { useSessionCredentials } from "@/api/use-session";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import type { CustomViewProps } from "../registry";

const insightSchema = z.object({
  total: z.number().int().nonnegative(),
  active: z.number().int().nonnegative(),
  draft: z.number().int().nonnegative(),
});

/// 项目运行洞察（旧 DemoItemInsight.vue 移植）：数据仍通过声明的 Action 获取。
export default function DemoItemInsight({
  presentation,
  actions,
  onClose,
}: CustomViewProps) {
  const session = useSessionCredentials();
  const [insight, setInsight] = useState<z.infer<typeof insightSchema>>();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const abortRef = useRef<AbortController | undefined>(undefined);

  const action = actions.find(
    (candidate) => candidate.operation_id === presentation.operation_id,
  );

  const load = useCallback(async () => {
    if (!action) {
      setError(`目录缺少 ${presentation.operation_id}`);
      return;
    }
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;
    setLoading(true);
    setError("");
    try {
      const result = await invokeAction(action, {}, session, controller.signal);
      if (result.kind !== "json") throw new Error("洞察 Action 必须返回 JSON");
      setInsight(insightSchema.parse(result.data));
    } catch (cause) {
      if (cause instanceof Error && cause.name === "AbortError") return;
      setError(cause instanceof Error ? cause.message : String(cause));
    } finally {
      if (abortRef.current === controller) setLoading(false);
    }
  }, [action, presentation.operation_id, session]);

  useEffect(() => {
    void load();
    return () => abortRef.current?.abort();
  }, [load]);

  return (
    <section aria-label="项目运行洞察">
      <header className="mb-4 flex items-start justify-between gap-3">
        <div className="space-y-1">
          <Badge variant="secondary">自定义 View</Badge>
          <h2 className="text-lg font-semibold">项目运行洞察</h2>
          <p className="text-sm text-muted-foreground">
            由静态 view_id 注册表加载，数据仍通过声明的 Action 获取。
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={onClose}>
          返回通用表格
        </Button>
      </header>
      {error ? (
        <p
          role="alert"
          className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive"
        >
          {error}
        </p>
      ) : loading && !insight ? (
        <div className="grid grid-cols-3 gap-3">
          <Skeleton className="h-24" />
          <Skeleton className="h-24" />
          <Skeleton className="h-24" />
        </div>
      ) : insight ? (
        <div className="grid grid-cols-3 gap-3">
          <article className="rounded-lg border border-border p-4">
            <span className="text-sm text-muted-foreground">项目总数</span>
            <p className="mt-1 text-2xl font-semibold">{insight.total}</p>
          </article>
          <article className="rounded-lg border border-border p-4">
            <span className="text-sm text-muted-foreground">运行中</span>
            <p className="mt-1 text-2xl font-semibold">{insight.active}</p>
          </article>
          <article className="rounded-lg border border-border p-4">
            <span className="text-sm text-muted-foreground">草稿</span>
            <p className="mt-1 text-2xl font-semibold">{insight.draft}</p>
          </article>
        </div>
      ) : null}
    </section>
  );
}

// frontend/src/custom/DemoItemInsight.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
import { z } from "zod";
import { invokeAction, type SessionContext } from "@/api/client";
import type {
  ActionDemoSchema,
  ActionPresentationSchema,
} from "@/contracts/ui-catalog";

const props = defineProps<{
  presentation: ActionPresentationSchema;
  actions: ActionDemoSchema[];
  session: SessionContext;
}>();
const emit = defineEmits<{ close: [] }>();

const insightSchema = z.object({
  total: z.number().int().nonnegative(),
  active: z.number().int().nonnegative(),
  draft: z.number().int().nonnegative(),
});
const insight = ref<z.infer<typeof insightSchema>>();
const loading = ref(false);
const error = ref("");
let controller: AbortController | undefined;
const action = computed(() =>
  props.actions.find(
    (candidate) => candidate.operation_id === props.presentation.operation_id,
  ),
);

async function load() {
  if (!action.value) {
    error.value = `目录缺少 ${props.presentation.operation_id}`;
    return;
  }
  controller?.abort();
  controller = new AbortController();
  loading.value = true;
  error.value = "";
  try {
    const result = await invokeAction(
      action.value,
      {},
      props.session,
      controller.signal,
    );
    if (result.kind !== "json") throw new Error("洞察 Action 必须返回 JSON");
    insight.value = insightSchema.parse(result.data);
  } catch (cause) {
    if (cause instanceof Error && cause.name === "AbortError") return;
    error.value = cause instanceof Error ? cause.message : String(cause);
  } finally {
    loading.value = false;
  }
}

onMounted(() => void load());
onBeforeUnmount(() => controller?.abort());
</script>

<template>
  <section class="custom-insight" v-loading="loading">
    <header class="custom-insight-heading">
      <div>
        <el-tag effect="dark">自定义 View</el-tag>
        <h2>项目运行洞察</h2>
        <p>由静态 view_id 注册表加载，数据仍通过声明的 Action 获取。</p>
      </div>
      <el-button @click="emit('close')">返回通用表格</el-button>
    </header>
    <el-alert
      v-if="error"
      type="error"
      :title="error"
      :closable="false"
      show-icon
    />
    <div v-else-if="insight" class="insight-metrics">
      <article>
        <span>项目总数</span>
        <strong>{{ insight.total }}</strong>
      </article>
      <article>
        <span>运行中</span>
        <strong>{{ insight.active }}</strong>
      </article>
      <article>
        <span>草稿</span>
        <strong>{{ insight.draft }}</strong>
      </article>
    </div>
  </section>
</template>
