// frontend-v2/src/renderers/table/TableView.tsx
import { useMemo, useState } from "react";
import { MoreHorizontal, RefreshCw } from "lucide-react";

import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { buildTreeRows } from "@/contracts/table-data";
import type {
  ActionDemoSchema,
  ActionPresentationSchema,
  TableViewSchema,
} from "@/contracts/ui-catalog";
import {
  ActionDialog,
  ConfirmActionDialog,
} from "@/renderers/action/ActionDialog";
import { usePresentedActions } from "@/renderers/action/use-presented-actions";
import { DataGrid } from "./DataGrid";
import { TableQueryPanel } from "./TableQueryPanel";
import { hasActiveQuery } from "./table-query";
import {
  createTableFilters,
  flattenDisplayRows,
  type SourceRow,
} from "./table-view-model";
import { useRelationOptions } from "./use-relation-options";
import { useTableQuery } from "./use-table-query";

function actionLabel(presentation: ActionPresentationSchema) {
  return presentation.title || presentation.operation_id;
}

/**
 * 通用 TableView 解释器（对齐旧 TableView.vue 编排）：
 * 查询面板 + TanStack Table 数据网格 + 行/批量/工具栏 Action + Action 对话框。
 */
export function TableView({
  view,
  actions,
}: {
  view: TableViewSchema;
  actions: ActionDemoSchema[];
}) {
  const dataAction = actions.find(
    (action) => action.operation_id === view.data_action,
  );
  const query = useTableQuery(view, dataAction);
  const [dense, setDense] = useState(false);
  const [selectedRows, setSelectedRows] = useState<SourceRow[]>([]);

  // 树视图在无查询条件时把扁平行构造为树；构造失败安全降级为普通表格。
  const treeResult = useMemo(() => {
    if (!view.tree || hasActiveQuery(query.state)) {
      return { rows: query.rows, warning: "" };
    }
    try {
      return { rows: buildTreeRows(query.rows, view.tree), warning: "" };
    } catch (cause) {
      return {
        rows: query.rows,
        warning: `${cause instanceof Error ? cause.message : String(cause)}；已安全降级为普通表格`,
      };
    }
  }, [view.tree, query.state, query.rows]);
  const displayRows = useMemo(
    () => flattenDisplayRows(treeResult.rows),
    [treeResult.rows],
  );

  const relation = useRelationOptions(view, actions, query.rows);

  const presented = usePresentedActions({
    presentations: view.action_presentations,
    businessFields: view.form.fields,
    actions,
    selectedRows,
    reload: query.reload,
  });

  const sort = {
    field: query.state.orderBy[0]?.field ?? null,
    descending: query.state.orderBy[0]?.direction === "desc",
  };

  return (
    <section aria-label={view.title || view.table}>
      <header className="mb-3 flex flex-wrap items-start justify-between gap-2">
        <div>
          <h2 className="text-lg font-semibold">{view.title || view.table}</h2>
          <p className="text-sm text-muted-foreground">
            共 {query.total} 项 · 支持搜索、筛选、排序和批量处理
          </p>
        </div>
        <div className="flex items-center gap-2">
          {presented.directToolbarActions.map((presentation) => (
            <Button
              key={presentation.operation_id}
              variant={
                presentation === presented.toolbarActionGroups.primary
                  ? "default"
                  : "outline"
              }
              size="sm"
              disabled={presentation.availability?.state === "disabled"}
              title={presentation.availability?.reason}
              onClick={() => presented.openAction(presentation)}
            >
              {actionLabel(presentation)}
            </Button>
          ))}
          {presented.toolbarActionGroups.overflow.length > 0 && (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="sm" aria-label="更多工具操作">
                  <MoreHorizontal className="size-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                {presented.toolbarActionGroups.overflow.map((presentation) => (
                  <DropdownMenuItem
                    key={presentation.operation_id}
                    disabled={presentation.availability?.state === "disabled"}
                    onClick={() => presented.openAction(presentation)}
                  >
                    {actionLabel(presentation)}
                  </DropdownMenuItem>
                ))}
              </DropdownMenuContent>
            </DropdownMenu>
          )}
          <Button
            variant="ghost"
            size="icon"
            aria-label="刷新数据"
            onClick={() => void query.reload()}
          >
            <RefreshCw className="size-4" />
          </Button>
        </div>
      </header>

      <TableQueryPanel
        view={view}
        state={query.state}
        dense={dense}
        onDenseChange={setDense}
        onStateChange={(patch) => {
          if (patch.filters) query.setFilters(patch.filters);
          if (patch.search !== undefined) query.setSearch(patch.search);
        }}
        onApply={() => {
          query.applyQuery();
          void query.reload();
        }}
        onReset={() => {
          query.setFilters(
            createTableFilters(
              view.columns.filter((column) =>
                view.query.filter_fields.includes(column.field),
              ),
            ),
          );
          query.setSearch("");
          query.applyQuery();
          void query.reload();
        }}
      />

      {treeResult.warning && (
        <p className="mb-3 rounded-md border border-border bg-muted/50 px-3 py-2 text-sm text-muted-foreground">
          {treeResult.warning}
        </p>
      )}
      {query.error && (
        <p
          role="alert"
          className="mb-3 rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive"
        >
          {query.error}
        </p>
      )}

      {presented.bulkActions.length > 0 && (
        <div className="mb-2 flex items-center gap-2 text-sm">
          <span className="text-muted-foreground">
            已选 {selectedRows.length} 项
          </span>
          {presented.bulkActions.map((presentation) => (
            <Button
              key={presentation.operation_id}
              variant="outline"
              size="sm"
              disabled={
                selectedRows.length === 0 ||
                presentation.availability?.state === "disabled"
              }
              title={presentation.availability?.reason}
              onClick={() => presented.openAction(presentation)}
            >
              {actionLabel(presentation)}
            </Button>
          ))}
        </div>
      )}

      <DataGrid
        view={view}
        rows={displayRows}
        loading={query.loading}
        dense={dense}
        sort={sort}
        onSortChange={query.changeSort}
        labelFor={relation.labelFor}
        selectionEnabled={presented.bulkActions.length > 0}
        onSelectionChange={setSelectedRows}
        rowActionGroups={presented.rowActionGroups}
        onOpenAction={presented.openAction}
      />

      <footer className="mt-3 flex flex-wrap items-center justify-end gap-2 text-sm">
        <span className="text-muted-foreground">
          第 {query.state.page} / {query.pageCount} 页 · 共 {query.total} 项
        </span>
        <select
          className="h-8 rounded-md border border-input bg-transparent px-2 text-sm"
          aria-label="每页条数"
          value={query.state.pageSize}
          onChange={(event) => query.changePageSize(Number(event.target.value))}
        >
          {query.pageSizeOptions.map((option) => (
            <option key={option.value} value={option.value}>
              {option.label}
            </option>
          ))}
        </select>
        <Button
          variant="outline"
          size="sm"
          disabled={query.state.page <= 1}
          onClick={() => query.changePage(query.state.page - 1)}
        >
          上一页
        </Button>
        <Button
          variant="outline"
          size="sm"
          disabled={query.state.page >= query.pageCount}
          onClick={() => query.changePage(query.state.page + 1)}
        >
          下一页
        </Button>
      </footer>

      {presented.notice && (
        <div
          role="status"
          className={
            presented.notice.type === "negative"
              ? "fixed right-4 bottom-4 rounded-md border border-destructive/40 bg-destructive/10 px-4 py-2 text-sm text-destructive shadow-lg"
              : "fixed right-4 bottom-4 rounded-md border border-border bg-background px-4 py-2 text-sm shadow-lg"
          }
        >
          {presented.notice.message}
          <button
            type="button"
            className="ml-3 text-muted-foreground hover:text-foreground"
            aria-label="关闭通知"
            onClick={presented.dismissNotice}
          >
            ✕
          </button>
        </div>
      )}

      <ActionDialog
        state={presented.dialog}
        businessFields={view.form.fields}
        actions={actions}
        submitting={presented.submitting}
        onClose={presented.closeDialog}
        onSubmit={presented.submitDialog}
      />
      <ConfirmActionDialog
        presentation={presented.confirmation}
        onSettle={presented.settleConfirmation}
      />
    </section>
  );
}

// frontend/src/components/table/TableView.vue
<script setup lang="ts">
import { computed } from "vue";
import { type QTableColumn } from "quasar";
import type { SessionContext } from "src/api/client";
import { buildTreeRows } from "src/contracts/table-data";
import type {
  ActionDemoSchema,
  ActionPresentationSchema,
  TableColumnSchema,
  TableViewSchema,
} from "src/contracts/ui-catalog";
import TableActionDialog from "./TableActionDialog.vue";
import TableDataGrid from "./TableDataGrid.vue";
import TableQueryPanel from "./TableQueryPanel.vue";
import { flattenDisplayRows, type DisplayRow } from "./table-view-model";
import { useColumnPreferences } from "./composables/useColumnPreferences";
import { useRelationOptions } from "./composables/useRelationOptions";
import { useTableActions } from "./composables/useTableActions";
import { useTableQuery } from "./composables/useTableQuery";
import { useTableSelection } from "./composables/useTableSelection";

const props = defineProps<{
  view: TableViewSchema;
  actions: ActionDemoSchema[];
  session: SessionContext;
  developer?: boolean;
  presentationSubmitLabel?: boolean;
}>();
const emit = defineEmits<{
  customAction: [
    presentation: ActionPresentationSchema,
    row?: Record<string, unknown>,
  ];
}>();

const actionById = computed(
  () => new Map(props.actions.map((action) => [action.operation_id, action])),
);
const dataAction = computed(() => actionById.value.get(props.view.data_action));
const relationState = useRelationOptions({
  view: () => props.view,
  actions: () => props.actions,
  session: () => props.session,
});
const { relationOptions, relationErrors } = relationState;
const queryState = useTableQuery({
  view: () => props.view,
  dataAction,
  session: () => props.session,
  onRowsLoaded: relationState.load,
  onLoadError: relationState.clear,
});
const {
  rows,
  total,
  page,
  pageSize,
  search,
  filters,
  filtersOpen,
  loading,
  error,
  tablePagination,
  activeFilterColumns,
  activeFilterCount,
  hasActiveQuery,
  pageCount,
  pageSizeOptions,
  load,
  applyQuery,
  changeSort,
  changePage,
  changePageSize,
  setFilterOperator,
  setFilterValue,
  clearFilter,
  clearAllQuery,
} = queryState;
const treeResult = computed(() => {
  if (!props.view.tree || hasActiveQuery.value)
    return { rows: rows.value, warning: "" };
  try {
    return { rows: buildTreeRows(rows.value, props.view.tree), warning: "" };
  } catch (cause) {
    return {
      rows: rows.value,
      warning: `${cause instanceof Error ? cause.message : String(cause)}；已安全降级为普通表格`,
    };
  }
});
const displayRows = computed(() => treeResult.value.rows);
const qTableRows = computed(() => flattenDisplayRows(displayRows.value));
const selectionState = useTableSelection(qTableRows);
const { selectedDisplayRows, selectedRows } = selectionState;
const tableActions = useTableActions({
  view: () => props.view,
  actions: () => props.actions,
  session: () => props.session,
  selectedRows,
  reload: load,
  emitCustom: (presentation, row) => {
    emit("customAction", presentation, row);
  },
});
const {
  actionDialog,
  actionLoading,
  activePresentation,
  activeAction,
  actionValues,
  rowActions,
  bulkActions,
  toolbarActionGroups,
  directToolbarActions,
  rowActionGroups,
  directRowActions,
  openAction,
  submitAction,
} = tableActions;
const columnPreferences = useColumnPreferences(
  () => props.view,
  () => rowActions.value.length > 0,
);
const { visibleColumnNames, visibleColumns, denseTable, setColumnVisible } =
  columnPreferences;
const tableColumns = computed<QTableColumn<DisplayRow>[]>(() => {
  const columns: QTableColumn<DisplayRow>[] = props.view.columns.map(
    (column) => ({
      name: column.field,
      label: column.title || column.field,
      field: (row) => row.data[column.field],
      align: column.display?.align ?? "left",
      sortable: column.sortable,
      style: column.display?.width
        ? `width: ${column.display.width}px`
        : column.display?.min_width
          ? `min-width: ${column.display.min_width}px`
          : undefined,
      headerStyle: column.display?.width
        ? `width: ${column.display.width}px`
        : column.display?.min_width
          ? `min-width: ${column.display.min_width}px`
          : undefined,
    }),
  );
  if (rowActions.value.length) {
    columns.push({
      name: "__actions",
      label: "操作",
      field: () => "",
      align: "right",
    });
  }
  return columns;
});
const columnByField = computed(
  () => new Map(props.view.columns.map((column) => [column.field, column])),
);
const firstColumnName = computed(() => props.view.columns[0]?.field);

function actionLabel(presentation: ActionPresentationSchema) {
  return presentation.title || presentation.operation_id;
}

function isDangerAction(presentation: ActionPresentationSchema) {
  return (
    presentation.appearance?.emphasis === "danger" ||
    Boolean(presentation.confirmation)
  );
}

function actionColor(presentation: ActionPresentationSchema) {
  return isDangerAction(presentation) ? "negative" : "primary";
}

function relationLabel(column: TableColumnSchema, value: unknown) {
  if (!column.relation) return undefined;
  return relationState.labelFor(column.relation.operation_id, value);
}
</script>

<template>
  <section class="table-view">
    <header class="table-view-heading">
      <div>
        <q-badge v-if="developer" outline color="primary">
          {{ view.view_id }}
        </q-badge>
        <h2>{{ view.title || view.table }}</h2>
        <p v-if="developer">
          {{ view.columns.length }} 个可见字段 · 数据源 {{ view.data_action }}
        </p>
        <p v-else>
          共 {{ total }} 项 · 支持搜索、筛选、排序和批量处理
          <q-icon
            v-if="relationErrors.length"
            name="warning_amber"
            color="warning"
            size="16px"
          >
            <q-tooltip>{{ relationErrors.join("；") }}</q-tooltip>
          </q-icon>
        </p>
      </div>
      <div class="view-actions">
        <q-btn
          v-for="presentation in directToolbarActions"
          :key="presentation.operation_id"
          :disabled="presentation.availability?.state === 'disabled'"
          :title="presentation.availability?.reason"
          :outline="presentation !== toolbarActionGroups.primary"
          :color="actionColor(presentation)"
          :icon="presentation.appearance?.icon"
          :label="actionLabel(presentation)"
          @click="openAction(presentation)"
        />
        <q-btn
          v-if="toolbarActionGroups.overflow.length"
          flat
          round
          color="primary"
          icon="more_horiz"
          aria-label="更多工具操作"
        >
          <q-menu auto-close>
            <q-list class="action-menu-list">
              <q-item
                v-for="presentation in toolbarActionGroups.overflow"
                :key="presentation.operation_id"
                clickable
                :disable="presentation.availability?.state === 'disabled'"
                @click="openAction(presentation)"
              >
                <q-item-section avatar>
                  <q-icon
                    :name="presentation.appearance?.icon || 'arrow_forward'"
                    :color="actionColor(presentation)"
                  />
                </q-item-section>
                <q-item-section>{{ actionLabel(presentation) }}</q-item-section>
              </q-item>
            </q-list>
          </q-menu>
        </q-btn>
        <q-btn
          flat
          round
          color="primary"
          icon="refresh"
          aria-label="刷新数据"
          :loading="loading"
          @click="load"
        />
      </div>
    </header>

    <TableQueryPanel
      :view="view"
      :search="search"
      :filters="filters"
      :filters-open="filtersOpen"
      :active-filter-count="activeFilterCount"
      :active-filter-columns="activeFilterColumns"
      :has-active-query="hasActiveQuery"
      :relation-options="relationOptions"
      :visible-column-names="visibleColumnNames"
      :dense-table="denseTable"
      @update:search="search = $event"
      @update:filters-open="filtersOpen = $event"
      @update:dense-table="denseTable = $event"
      @apply="applyQuery"
      @set-filter-operator="setFilterOperator"
      @set-filter-value="setFilterValue"
      @clear-filter="clearFilter"
      @clear-all="clearAllQuery"
      @set-column-visible="setColumnVisible"
    />

    <TableDataGrid
      v-model:selected="selectedDisplayRows"
      :view="view"
      :error="error"
      :tree-warning="treeResult.warning"
      :bulk-actions="bulkActions"
      :selected-rows="selectedRows"
      :rows="qTableRows"
      :columns="tableColumns"
      :visible-columns="visibleColumns"
      :loading="loading"
      :pagination="tablePagination"
      :dense="denseTable"
      :direct-row-actions="directRowActions"
      :row-action-groups="rowActionGroups"
      :column-by-field="columnByField"
      :first-column-name="firstColumnName"
      :total="total"
      :page-size="pageSize"
      :page-size-options="pageSizeOptions"
      :page="page"
      :page-count="pageCount"
      :has-active-query="hasActiveQuery"
      :relation-label="relationLabel"
      @open-action="openAction"
      @update-pagination="changeSort"
      @change-page-size="changePageSize"
      @change-page="changePage"
    />

    <TableActionDialog
      v-model="actionDialog"
      v-model:values="actionValues"
      :active-presentation="activePresentation"
      :active-action="activeAction"
      :business-fields="view.form.fields"
      :actions="actions"
      :session="session"
      :loading="actionLoading"
      :submit-label="
        presentationSubmitLabel ? activePresentation?.title : undefined
      "
      @submit="submitAction"
    />
  </section>
</template>
