// frontend/src/pages/DashboardPage.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { storeToRefs } from "pinia";
import { useRouter } from "vue-router";
import {
  buildAccountModulePages,
  modulesForIdentity,
  unassignedViews,
} from "src/module-pages";
import { useApplicationLifecycleStore } from "stores/application-lifecycle";
import { useCatalogStore } from "stores/catalog";
import { useCatalogNavigationStore } from "stores/catalog-navigation";
import { useIdentityStore } from "stores/identity";
import { productLowerCase } from "src/product-locale";

const router = useRouter();
const catalogStore = useCatalogStore();
const navigationStore = useCatalogNavigationStore();
const identityStore = useIdentityStore();
const lifecycleStore = useApplicationLifecycleStore();
const { catalog, error, loading } = storeToRefs(catalogStore);
const { selectedViewId } = storeToRefs(navigationStore);
const { accountIdentity } = storeToRefs(identityStore);
const query = ref("");

const modulePages = computed(() => buildAccountModulePages(catalog.value));
const identityModules = computed(() =>
  modulesForIdentity(modulePages.value, accountIdentity.value),
);
const businessViews = computed(() => unassignedViews(catalog.value));
const filteredModules = computed(() => {
  const keyword = productLowerCase(query.value.trim());
  if (!keyword) return identityModules.value;
  return identityModules.value.filter((module) =>
    [module.id, module.title, module.description]
      .map(productLowerCase)
      .join(" ")
      .includes(keyword),
  );
});
const filteredViews = computed(() => {
  const keyword = productLowerCase(query.value.trim());
  if (!keyword) return businessViews.value;
  return businessViews.value.filter((view) =>
    [view.title, view.table, view.view_id]
      .filter(Boolean)
      .some((value) => productLowerCase(value).includes(keyword)),
  );
});

async function openBusinessView(viewId: string) {
  selectedViewId.value = viewId;
  await router.push("/business");
}

async function openModule(moduleId: string) {
  await router.push(`/module/${moduleId}`);
}
</script>

<template>
  <q-page padding class="dashboard-page">
    <div class="dashboard-title-row">
      <div>
        <h1>应用中心</h1>
        <p>选择当前账号可访问的业务模块</p>
      </div>
      <q-chip
        square
        outline
        color="primary"
        :icon="catalog ? 'cloud_done' : 'cloud_off'"
      >
        {{ catalog ? "服务已连接" : "等待服务" }}
      </q-chip>
    </div>

    <q-banner
      v-if="error"
      rounded
      class="dashboard-alert bg-red-1 text-negative"
    >
      <template #avatar><q-icon name="cloud_off" /></template>
      {{ error.message }}
      <template #action>
        <q-btn
          flat
          color="negative"
          label="重新加载"
          @click="lifecycleStore.reloadCatalog"
        />
      </template>
    </q-banner>

    <div
      v-if="identityModules.length + businessViews.length > 1"
      class="row no-gutters q-mb-lg"
    >
      <q-input
        v-model="query"
        outlined
        clearable
        label="搜索功能"
        class="col-12 col-md-6 offset-md-3"
      >
        <template #prepend><q-icon name="search" /></template>
      </q-input>
    </div>

    <div class="q-col-gutter-md row">
      <div
        v-for="module in filteredModules"
        :key="module.id"
        class="col-12 col-sm-6 col-md-4 col-lg-3"
      >
        <q-card
          flat
          bordered
          class="application-card cursor-pointer full-height"
          :data-testid="`module-page-${module.id}`"
          @click="openModule(module.id)"
        >
          <q-card-section horizontal>
            <q-card-section class="row items-center">
              <q-avatar
                color="primary"
                text-color="white"
                size="72px"
                :icon="module.icon"
              />
            </q-card-section>
            <q-separator vertical inset />
            <q-card-section class="full-width">
              <q-item dense>
                <q-item-section>
                  <q-item-label class="text-h6">{{
                    module.title
                  }}</q-item-label>
                </q-item-section>
                <q-item-section side>
                  <q-item-label caption>{{ module.id }}</q-item-label>
                </q-item-section>
              </q-item>
              <q-separator inset />
              <q-card-section class="text-caption text-grey-7">
                {{ module.description }}
              </q-card-section>
            </q-card-section>
          </q-card-section>
        </q-card>
      </div>

      <div
        v-for="view in filteredViews"
        :key="view.view_id"
        class="col-12 col-sm-6 col-md-4 col-lg-3"
      >
        <q-card
          flat
          bordered
          class="application-card cursor-pointer full-height"
          @click="openBusinessView(view.view_id)"
        >
          <q-card-section horizontal>
            <q-card-section class="row items-center">
              <q-avatar
                color="primary"
                text-color="white"
                size="72px"
                icon="view_list"
              />
            </q-card-section>
            <q-separator vertical inset />
            <q-card-section class="full-width">
              <q-item dense>
                <q-item-section>
                  <q-item-label class="text-h6">{{
                    view.title || view.table
                  }}</q-item-label>
                </q-item-section>
                <q-item-section side>
                  <q-item-label caption>{{ view.table }}</q-item-label>
                </q-item-section>
              </q-item>
              <q-separator inset />
              <q-card-section class="text-caption text-grey-7 ellipsis">
                {{ view.columns.length }} 个字段 · 契约驱动页面
              </q-card-section>
            </q-card-section>
          </q-card-section>
        </q-card>
      </div>
    </div>

    <q-inner-loading :showing="loading">
      <q-spinner color="primary" size="48px" />
    </q-inner-loading>
  </q-page>
</template>

// frontend/src/pages/DashboardPage.tsx
import { useEffect, useState } from "react";
import { Search } from "lucide-react";
import { Link, Navigate, useOutletContext } from "react-router";

import { useIdentity } from "@/app/use-identity";
import { Input } from "@/components/ui/input";
import {
  buildAccountModulePages,
  modulesForIdentity,
  unassignedViews,
  visibleAccountIdentities,
} from "@/engine/catalog/module-pages";
import type { ShellContext } from "@/layout/AppLayout";
import { productLowerCase } from "@/lib/product-locale";

/// 应用中心（旧 DashboardPage.vue 语义）：身份过滤后的模块卡片 + 未分配视图入口。
export default function DashboardPage() {
  const { catalog } = useOutletContext<ShellContext>();
  const { identity, select } = useIdentity();
  const [query, setQuery] = useState("");

  const modulePages = buildAccountModulePages(catalog);
  const identities = visibleAccountIdentities(modulePages, catalog);

  // 单身份账号直接进入（旧语义：/roles 手动选择；M3 起单身份免选）。
  useEffect(() => {
    if (!identity && identities.length === 1 && identities[0]) {
      select(identities[0].id);
    }
  }, [identity, identities, select]);

  // 多身份且未选择（或所选身份已不可见）→ 选择页。
  if (
    identities.length > 1 &&
    (!identity || !identities.some((candidate) => candidate.id === identity))
  ) {
    return <Navigate to="/select-identity" replace />;
  }

  const keyword = productLowerCase(query.trim());
  const modules = modulesForIdentity(modulePages, identity).filter((module) =>
    keyword
      ? [module.id, module.title, module.description]
          .map(productLowerCase)
          .join(" ")
          .includes(keyword)
      : true,
  );
  const businessViews = unassignedViews(catalog).filter((view) =>
    keyword
      ? [view.title, view.table, view.view_id]
          .filter(Boolean)
          .some((value) => productLowerCase(value).includes(keyword))
      : true,
  );

  return (
    <div className="p-6">
      <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="text-xl font-semibold tracking-tight">应用中心</h1>
          <p className="text-sm text-muted-foreground">
            选择当前账号可访问的业务模块
          </p>
        </div>
        <span className="rounded-md border border-border px-2 py-1 text-xs text-muted-foreground">
          服务已连接
        </span>
      </div>

      {modules.length + businessViews.length > 1 && (
        <div className="relative mb-6 max-w-md">
          <Search className="absolute top-2.5 left-3 size-4 text-muted-foreground" />
          <Input
            className="pl-9"
            placeholder="搜索功能"
            aria-label="搜索功能"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
          />
        </div>
      )}

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {modules.map((module) => (
          <Link
            key={module.id}
            to={`/m/${module.id}`}
            data-testid={`module-card-${module.id}`}
            className="rounded-lg border border-border bg-card p-5 transition-colors hover:border-primary/50"
          >
            <h2 className="font-semibold">{module.title}</h2>
            <p className="mt-1 text-xs text-muted-foreground">{module.id}</p>
            <p className="mt-2 line-clamp-2 text-sm text-muted-foreground">
              {module.description}
            </p>
          </Link>
        ))}
        {businessViews.map((view) => (
          <Link
            key={view.view_id}
            to={`/business?view=${encodeURIComponent(view.view_id)}`}
            data-testid={`view-card-${view.view_id}`}
            className="rounded-lg border border-border bg-card p-5 transition-colors hover:border-primary/50"
          >
            <h2 className="font-semibold">{view.title || view.table}</h2>
            <p className="mt-1 text-xs text-muted-foreground">{view.table}</p>
            <p className="mt-2 text-sm text-muted-foreground">
              {view.columns.length} 个字段 · 契约驱动页面
            </p>
          </Link>
        ))}
      </div>

      {modules.length + businessViews.length === 0 && (
        <p className="py-12 text-center text-sm text-muted-foreground">
          当前身份没有可访问的业务模块。
        </p>
      )}
    </div>
  );
}
