// frontend/src/pages/ResetPasswordPage.vue
<script setup lang="ts">
import { ref } from "vue";
import { useRouter } from "vue-router";
import { resetPassword } from "src/api/auth";
import { publishSessionEnd } from "src/api/session-coordination";
import { useApplicationSession } from "src/composables/useApplicationSession";

const router = useRouter();
const applicationSession = useApplicationSession();
const resetToken = ref("");
const newPassword = ref("");
const confirmPassword = ref("");
const submitting = ref(false);
const errorMessage = ref("");
const passwordVisible = ref(false);

async function submit() {
  if (submitting.value) return;
  errorMessage.value = "";
  if (newPassword.value !== confirmPassword.value) {
    errorMessage.value = "两次输入的新密码不一致";
    return;
  }
  submitting.value = true;
  try {
    await resetPassword(resetToken.value.trim(), newPassword.value);
    resetToken.value = "";
    newPassword.value = "";
    confirmPassword.value = "";
    applicationSession.clearSession();
    publishSessionEnd("credentials-changed");
    await router.replace({
      name: "login",
      query: { reason: "credentials-changed" },
    });
  } catch (cause) {
    errorMessage.value =
      cause instanceof Error ? cause.message : "密码重置失败，请稍后重试";
  } finally {
    submitting.value = false;
  }
}
</script>

<template>
  <main
    class="reset-password-page row items-center justify-center q-pa-md bg-grey-2"
  >
    <q-card class="reset-password-card">
      <q-card-section>
        <h1 class="text-h5 q-my-none">重置密码</h1>
        <p class="text-grey-7 q-mb-none">
          输入管理员通过受控渠道交付的一次性凭证。凭证成功使用后立即失效。
        </p>
      </q-card-section>
      <q-separator />
      <q-form class="q-pa-lg q-gutter-md" @submit.prevent="submit">
        <q-input
          v-model="resetToken"
          name="reset_token"
          label="重置凭证"
          type="password"
          autocomplete="one-time-code"
          filled
          :rules="[
            (value: string) => Boolean(value.trim()) || '请输入重置凭证',
          ]"
        />
        <q-input
          v-model="newPassword"
          name="new_password"
          label="新密码"
          :type="passwordVisible ? 'text' : 'password'"
          autocomplete="new-password"
          filled
          :rules="[
            (value: string) => value.length >= 10 || '新密码至少 10 个字符',
          ]"
        >
          <template #append>
            <q-icon
              :name="passwordVisible ? 'visibility' : 'visibility_off'"
              class="cursor-pointer"
              @click="passwordVisible = !passwordVisible"
            />
          </template>
        </q-input>
        <q-input
          v-model="confirmPassword"
          name="confirm_password"
          label="确认新密码"
          :type="passwordVisible ? 'text' : 'password'"
          autocomplete="new-password"
          filled
          :rules="[
            (value: string) =>
              value === newPassword || '两次输入的新密码不一致',
          ]"
        />
        <q-banner v-if="errorMessage" rounded class="bg-red-1 text-negative">
          {{ errorMessage }}
        </q-banner>
        <q-btn
          type="submit"
          color="primary"
          label="重置密码"
          unelevated
          size="lg"
          class="full-width"
          :loading="submitting"
        />
        <q-btn flat label="返回登录" class="full-width" to="/login" />
      </q-form>
    </q-card>
  </main>
</template>

<style scoped>
.reset-password-page {
  min-height: 100vh;
}

.reset-password-card {
  width: min(100%, 480px);
}
</style>

// frontend/src/pages/ResetPasswordPage.tsx
import { useState, type FormEvent } from "react";
import { Link, useNavigate, useSearchParams } from "react-router";

import { resetPassword } from "@/engine/session/auth";
import { publishSessionEnd } from "@/engine/session/session-coordination";
import { useSessionController } from "@/engine/session/use-session";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

/// 重置密码（旧 ResetPasswordPage.vue 语义）：一次性凭证 + 新密码；
/// 凭证可由链接 query（?token=）预填。成功后清空会话并广播凭据变更。
export default function ResetPasswordPage() {
  const controller = useSessionController();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [resetToken, setResetToken] = useState(searchParams.get("token") ?? "");
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");
  const [passwordVisible, setPasswordVisible] = useState(false);

  const submit = async (event: FormEvent) => {
    event.preventDefault();
    if (submitting) return;
    setErrorMessage("");
    if (!resetToken.trim()) {
      setErrorMessage("请输入重置凭证");
      return;
    }
    if (newPassword.length < 10) {
      setErrorMessage("新密码至少 10 个字符");
      return;
    }
    if (newPassword !== confirmPassword) {
      setErrorMessage("两次输入的新密码不一致");
      return;
    }
    setSubmitting(true);
    try {
      await resetPassword(resetToken.trim(), newPassword);
      setResetToken("");
      setNewPassword("");
      setConfirmPassword("");
      controller.clearSession("credentials-changed");
      publishSessionEnd("credentials-changed");
      navigate("/login", { replace: true });
    } catch (cause) {
      setErrorMessage(
        cause instanceof Error ? cause.message : "密码重置失败，请稍后重试",
      );
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <main className="flex min-h-svh items-center justify-center bg-muted/40 px-4 py-8">
      <div className="w-full max-w-md rounded-xl border border-border bg-card p-8 shadow-sm">
        <div className="mb-6 space-y-1">
          <h1 className="text-xl font-semibold">重置密码</h1>
          <p className="text-sm text-muted-foreground">
            输入管理员通过受控渠道交付的一次性凭证。凭证成功使用后立即失效。
          </p>
        </div>
        <form className="space-y-4" onSubmit={submit} noValidate>
          <div className="space-y-1.5">
            <Label htmlFor="reset-token">重置凭证</Label>
            <Input
              id="reset-token"
              type="password"
              autoComplete="one-time-code"
              value={resetToken}
              onChange={(event) => setResetToken(event.target.value)}
            />
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="reset-new-password">新密码</Label>
            <div className="relative">
              <Input
                id="reset-new-password"
                type={passwordVisible ? "text" : "password"}
                autoComplete="new-password"
                className="pr-16"
                value={newPassword}
                onChange={(event) => setNewPassword(event.target.value)}
              />
              <button
                type="button"
                className="absolute top-2 right-3 text-xs text-muted-foreground hover:text-foreground"
                onClick={() => setPasswordVisible((prev) => !prev)}
              >
                {passwordVisible ? "隐藏" : "显示"}
              </button>
            </div>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="reset-confirm-password">确认新密码</Label>
            <Input
              id="reset-confirm-password"
              type={passwordVisible ? "text" : "password"}
              autoComplete="new-password"
              value={confirmPassword}
              onChange={(event) => setConfirmPassword(event.target.value)}
            />
          </div>

          {errorMessage && (
            <p
              role="alert"
              className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-destructive"
            >
              {errorMessage}
            </p>
          )}

          <Button type="submit" className="w-full" disabled={submitting}>
            {submitting ? "提交中…" : "重置密码"}
          </Button>
          <Button variant="ghost" className="w-full" asChild>
            <Link to="/login">返回登录</Link>
          </Button>
        </form>
      </div>
    </main>
  );
}
